[build]
  publish = "public"
  command = "git submodule update --init --recursive && npm install && hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.139.4"

[context.deploy-preview]
  command = "git submodule update --init --recursive && npm install && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "git submodule update --init --recursive && npm install && hugo --gc --minify -b $DEPLOY_PRIME_URL"
